#!/bin/bash

vd_home=`pwd`
docker_repo=forthev/vd

os_type=`uname`

if [ "$os_type" == "Darwin" ]; then
for i in en0 en1 en2; do
  ip_addr=${ip_addr:-`/sbin/ifconfig $i | sed -ne '/inet/ s/.*inet \([0-9.]*\).*/\\1/p'`}
done
else
for i in enp5s0 eth0 eth1 eth2 wlan0 wlan1 wlan2 ens33; do
  ip_addr=${ip_addr:-`/sbin/ip addr show $i | sed -ne '/inet/ s/.*inet \([0-9.]*\).*/\\1/p'`}
done
fi


if [ -z "$1" ]
then
echo "Usage: $0 [command]"
echo
echo "command can be:"
echo
echo "  - clone Vierte Dimension repository to current directory:"
echo "      fossil clone https://$USER@fossil.forth-ev.de/vd-JJJJ-0x vd-JJJJ-0x.fossil"
echo   
echo "  - expand fossil repository to current directory:"
echo "      fossil open vd-JJJJ-0x.fossil"
echo 
echo "  - other fossil command"
echo  
echo "  - typeset Vierte Dimension issue:"
echo "      make"
echo
echo "  - preview Vierte Dimension issue:"
echo "      mupdf 4dJJJJ-0x.pdf"
echo
echo "  - run Lyx editor:"
echo "      lyx [filename]"
echo 
echo "Graphical applications require an X-Server running at DISPLAY=$ip_addr:0"
echo
exit
fi

xhost +
set -x
docker run -i -t \
  -e USER=$USER \
  -e DISPLAY=$ip_addr:0 \
  -p 8080:8080 \
  -v "$vd_home":/VierteDimension --rm $docker_repo $*
xhost -
