name: Docker test build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
   push:
    branches:
      - master

env:
  CI_REGISTRY: registry.hub.docker.com

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker build
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          TAG: ${{env.CI_REGISTRY}}/forthev/vd:${{github.sha}}
          LATEST: ${{env.CI_REGISTRY}}/forthev/vd:latest
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $CI_REGISTRY
          docker build . -t $TAG
          docker push $TAG
          docker tag $TAG $LATEST
          docker push $LATEST
